---

#-------------------------------------------------------------------------------
# Create maintenance page
#-------------------------------------------------------------------------------

- name: Ensures /var/www/maintenance/ dir exists
  file: 
    path: /var/maintenance/
    state: directory

- name: "Install shifumi-maintenance version {{ shifumi_maintenance_version }}"
  git:
    repo: "{{ shifumi_maintenance_repo }}"
    dest: /var/maintenance/
    version: "{{ shifumi_maintenance_version }}"
    force: yes

- name: "Create symbolic link"
  file:
    src: "/var/maintenance/"
    dest: "/var/www/maintenance"
    state: link
