---

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - geerlingguy.certbot
    - geerlingguy.nginx
    - geerlingguy.nodejs
    - shifumi.maintenance
    # - shifumi.mongodb
    - weareinteractive.pm2
  # shared var files
  vars_files:
    - inventory/shared/certbot.yml
    - inventory/shared/nginx.yml
    - inventory/shared/nodejs.yml
    - inventory/shared/pm2.yml
    - inventory/shared/shifumi.yml
  # tasks will be executed after roles
  tasks:
    - debug:
        msg: "Nodejs {{ nodejs_version }} is ready"
    - debug:
        msg: "pm2 is ready with user {{ pm2_user }}"
    - name: "Update npm package"
      shell: npm install -g npm
