# please see https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html
# - src: git repository
#   version: tag name
#   name: ansible repo

# geerlingguy from galaxy
- src: geerlingguy.nodejs
- src: geerlingguy.nginx
- src: geerlingguy.certbot
- src: geerlingguy.php

# weareinteractive.pm2 from galaxy
- src: weareinteractive.pm2
