# please see https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html
# - src: git repository
#   version: tag name
#   name: ansible repo

# geerlingguy.nodejs from galaxy
- src: geerlingguy.nodejs

# weareinteractive.pm2 from galaxy
- src: weareinteractive.pm2

# robertdebock.npm from galaxy
- src: robertdebock.npm
