---

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - shifumi.socket
    - shifumi.api
    - shifumi.front
  tasks:
    - name: "Restart nginx"
      service: name=nginx state=reloaded
