---

#-------------------------------------------------------------------------------
# API
#-------------------------------------------------------------------------------

- debug: 
    msg: Start shifumi api install/update
