---

#-------------------------------------------------------------------------------
# API
#-------------------------------------------------------------------------------

- debug: 
    msg: Start shifumi api install/update

- name: "Install shifumi-api version {{ shifumi_api_version }}"
  git:
    repo: "{{ shifumi_api_repo }}"
    dest: /var/www/shifumi-api
    version: "{{ shifumi_api_version }}"
    force: yes

- name: "npm install"
  npm:
    path: /var/www/shifumi-api

- name: "Restart PM2"
  shell: "pm2 restart all"
