# values for geerlingguy.nginx
# nginx_user: "nginx"
nginx_vhosts:
  - listen: "80"
    server_name: "cbouche.me *.cbouche.me"
    access_log: "/var/log/nginx/cbouche.access.log"
    error_log: "/var/log/nginx/cbouche.error.log"
    extra_parameters: |
          # hide nginx version
          server_tokens off;

          if ($host = maintenance.cbouche.me) {
              return 301 http://$host$request_uri;
          }

          if ($host = shifumi.cbouche.me) {
              return 301 http://$host$request_uri;
          }

          if ($host = shaarli.cbouche.me) {
              return 301 http://$host$request_uri;
          }

          if ($host = api.cbouche.me) {
              return 301 http://$host$request_uri;
          }

          # redirection to maintenance
          if ($host = cbouche.me) {
              return 301 http://maintenance.cbouche.me$request_uri;
          }

          return 404; # managed by Certbot

  - listen: "80"
    server_name: "shaarli.cbouche.me"
    root: "/var/www/Shaarli"
    index: "index.php"
    access_log: "/var/log/nginx/shaarli.access.log"
    error_log: "/var/log/nginx/shaarli.error.log"
    extra_parameters: |
          # hide nginx version
          server_tokens off;

          # php application
          location ~(index)\.php$ {
            try_files $uri =404;
            fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
          }

  - listen: "80"
    server_name: "api.cbouche.me"
    access_log: "/var/log/nginx/api.access.log"
    error_log: "/var/log/nginx/api.error.log"
    extra_parameters: |
          # hide nginx version
          server_tokens off;

          # express nodejs API
          location / {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/;
            proxy_redirect http://127.0.0.1:3000/ https://api.cbouche.me/;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }

  - listen: "80"
    server_name: "maintenance.cbouche.me"
    root: "/var/www/maintenance"
    index: "index.html"
    access_log: "/var/log/nginx/maintenance.access.log"
    error_log: "/var/log/nginx/maintenance.error.log"
    extra_parameters: |
          # hide nginx version
          server_tokens off;

          # angular application build
          location / {
            try_files $uri $uri/ /index.html;
          }

  - listen: "80"
    server_name: "shifumi.cbouche.me"
    root: "/var/www/shifumi"
    index: "index.html"
    access_log: "/var/log/nginx/shifumi.access.log"
    error_log: "/var/log/nginx/shifumi.error.log"
    extra_parameters: |
          # hide nginx version
          server_tokens off;

          # angular application build
          location / {
            try_files $uri $uri/ /index.html;
          }
