# values for geerlingguy.nginx
# nginx_user: "nginx"
nginx_vhosts:
  - listen: "80"
    server_name: "localhost"
    root: "/var/www/shifumi"
    index: "index.html"
    access_log: "/var/log/nginx/shifumi.access.log"
    error_log: "/var/log/nginx/shifumi.access.log"
    extra_parameters: |
          # relative path
          location /api/ {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/;
            proxy_redirect off;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }
          # angular build
          location / {
            try_files $uri $uri/ /index.html;
          }
          # certificate information
          # ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
          # ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
          # ssl_protocols       TLSv1.1 TLSv1.2;
          # ssl_ciphers         HIGH:!aNULL:!MD5;

  # - listen: "80"
  #   server_name: "api.localhost"
  #   access_log: "/var/log/nginx/api.shifumi.access.log"
  #   error_log: "/var/log/nginx/api.shifumi.access.log"
  #   extra_parameters: |
  #         # prox to pm2 api service running on localhost:3000
  #         location / {
  #           proxy_set_header Host $http_host;
  #           proxy_http_version 1.1;
  #           proxy_set_header Upgrade $http_upgrade;
  #           proxy_set_header Connection "upgrade";
  #           proxy_pass http://127.0.0.1:3000/;
  #           proxy_redirect off;
  #           proxy_read_timeout 240s;
  #           proxy_cache_bypass $http_upgrade;
  #         }
  #         # certificate information
  #         # ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
  #         # ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
  #         # ssl_protocols       TLSv1.1 TLSv1.2;
  #         # ssl_ciphers         HIGH:!aNULL:!MD5;
