# values for geerlingguy.nginx
# nginx_user: "nginx"
nginx_vhosts:
  - listen: "80"
    server_name: "default"
    extra_parameters: |
          # redirection to https
          if ($host = cbouche.me) {
              return 301 https://$host$request_uri;
          } # managed by Certbot
          
          return 404; # managed by Certbot

  - listen: "443 ssl"
    server_name: "cbouche.me"
    root: "/var/www"
    index: "index.html"
    access_log: "/var/log/nginx/shifumi.access.log"
    error_log: "/var/log/nginx/shifumi.error.log"
    extra_parameters: |
          # hide nginx version
          server_tokens off;

          # shaarli
          location /Shaarli/ {
            try_files $uri /Shaarli/index.php$is_args$args;
            access_log /var/log/nginx/shaarli.access.log;
            error_log  /var/log/nginx/shaarli.error.log;
          }

          # express nodejs API
          location /api/ {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/;
            proxy_redirect http://127.0.0.1:3000/ https://cbouche.me/api;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }

          # swagger documentation
          location /docs/ {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/docs/;
            proxy_redirect http://127.0.0.1:3000/docs/ https://cbouche.me/docs/;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }

          # angular application build
          location / {
            root /var/www/shifumi;
            try_files $uri $uri/ /index.html;
          }

          # php application
          location ~(index)\.php$ {
            try_files $uri =404;
            fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
          }

          # certificate information
          # managed by Certbot
          ssl_certificate     /etc/letsencrypt/live/cbouche.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/cbouche.me/privkey.pem;
          include             /etc/letsencrypt/options-ssl-nginx.conf;
          ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
