# values for geerlingguy.nginx
# nginx_user: "nginx"
nginx_vhosts:
  - listen: "80"
    server_name: "cbouche.me"
    root: "/var/www/shifumi"
    index: "index.html"
    access_log: "/var/log/nginx/cbouche.access.log"
    error_log: "/var/log/nginx/cbouche.error.log"
    extra_parameters: |
          # hide nginx version
          server_tokens off;

          # express nodejs API
          location /api/ {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/;
            proxy_redirect http://127.0.0.1:3000/ https://51.15.12.84/api/;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }

          # swagger documentation
          location /docs/ {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/docs/;
            proxy_redirect http://127.0.0.1:3000/docs/ https://51.15.12.84/docs/;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }

          # shaarli
          location /shaarli/ {
            root /var/www/Shaarli/;
            try_files $uri index.php$is_args$args;
          }

          # maintenance
          location /maintenance/ {
            root /var/www/maintenance/;
            index index.html;
            try_files $uri $uri/ /index.html;
          }

          # php application (shaarli)
          location ~(index)\.php$ {
            try_files $uri =404;
            fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
          }

          # angular application build
          location / {
            try_files $uri $uri/ /index.html;
          }
