# values for geerlingguy.nginx
# nginx_user: "nginx"
nginx_vhosts:
  - listen: "80"
    server_name: "default"
    extra_parameters: |
          # redirection to https
          if ($host = cbouche.me) {
              return 301 https://$host$request_uri;
          } # managed by Certbot
          
          return 404; # managed by Certbot

  - listen: "443 ssl"
    server_name: "cbouche.me"
    root: "/var/www/shifumi"
    index: "index.html"
    access_log: "/var/log/nginx/shifumi.access.log"
    error_log: "/var/log/nginx/shifumi.access.log"
    extra_parameters: |
          # express nodejs API
          location /api/ {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/;
            proxy_redirect http://127.0.0.1:3000/ https://cbouche.me/api;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }

          # swagger documentation
          location /docs/ {
            proxy_set_header Host $http_host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:3000/docs/;
            proxy_redirect http://127.0.0.1:3000/docs/ https://cbouche.me/docs/;
            proxy_read_timeout 240s;
            proxy_cache_bypass $http_upgrade;
          }

          # angular application build
          location / {
            try_files $uri $uri/ /index.html;
          }

          # certificate information
          # managed by Certbot
          ssl_certificate     /etc/letsencrypt/live/cbouche.me/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/cbouche.me/privkey.pem;
          include             /etc/letsencrypt/options-ssl-nginx.conf;
          ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
