# php config
php_memory_limit: '256M'
php_timezone: 'Europe/Paris'
php_max_execution_time: '90'
php_upload_max_filesize: '256M'
php_packages:
  - php
  - php-cli
  - php-common
  - php-curl
  - php-intl
  - php-json
  - php-ldap
  - php-sqlite3
  - php-pgsql
  - php-gd
  - php-mbstring
  - php-pdo
  - php-apcu
  - php-xml
  - php-zip
